services:
  netease-login:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netease-login
    restart: unless-stopped
    entrypoint: ["sh", "-c", "while true; do . /app/.env.local; python /app/main.py; sleep 3600; done"]
    # entrypoint: ["sh", "-c", "echo '0 8,20 * * * python /app/main.py' | crontab - && cron -f"]
    volumes:
      - .env.local:/app/.env.local:ro
      - type: bind
        source: ./login_record
        target: /app/login_record
        bind:
          create_host_path: true
    environment:
      SESSION_COOKIE: ""
      PYTHONUNBUFFERED: "1"

